#!/usr/bin/perl -w
use strict;

use Term::ANSIColor;
# usage:
# color("yellow"), color("bold red"), etc
# color("reset")

sub basename($)
{
	return $1 if $_[0] =~ m|.*/([^/]+)$|;
	return $_[0];
}

use constant HIGHLIGHT => "bold yellow";

my($lineno,$regex) = (0,undef);
my %filelist = ();

warn basename($0) . ": output isn't a terminal\n" if !-t STDOUT;

for(@ARGV){
	if($_ eq '-n'){
		$lineno = 1;
		shift @ARGV;
	}else{
		$regex = $_;
		shift @ARGV;
		last;
	}
}
die "Need regex\n" unless defined $regex;

while(<>){
	print $..": " if($lineno);
	if(m/$regex/io){
		print $`.color(HIGHLIGHT).$&.color("reset").$';
	}else{
		print $_;
	}
}
