#!/usr/bin/perl -w
use strict;

sub basename($)
{
	return $1 if $_[0] =~ m|.*/([^/]+)$|;
	return $_[0];
}


my($lineno,$regex) = (0,undef);
my %filelist = ();

my %grep_cols = map { split /=/ } split /:/, $ENV{GREP_COLORS};
my %colours  = (
	hl   => "\e[" . ($grep_cols{mt} or '1;31') . 'm',
	bg   => "\e[" . ($grep_cols{sl} or '1;30') . 'm',
	norm => "\e[0m"
);

warn basename($0) . ": output isn't a terminal\n" unless -t STDOUT;

for(@ARGV){
	if($_ eq '-n'){
		$lineno = 1;
		shift @ARGV;
	}else{
		$regex = $_;
		shift @ARGV;
		last;
	}
}
die "Need regex\n" unless defined $regex;

while(<>){
	print $colours{norm} . $. . ": " if($lineno);

	print $colours{bg};

	if(m/$regex/io){
		print $` . $colours{hl} . $& . $colours{bg} . $';
	}else{
		print $_;
	}
}
