#!/usr/bin/perl
use warnings;

sub usage()
{
	print "Usage: $0 [-n] [-5] [files...]\n";
	exit 1;
}

$nlines = 0;
# 0 means all on one line, otherwise join $nlines lines
$\ = "\n";


for(0 .. $#ARGV){
	$_ = $ARGV[$_];
	if(/^-([0-9]+)$/){
		usage if $nlines;
		$nlines = $1;
	}elsif($_ eq '-n'){
		usage unless $\;
		$\ = '';
	}else{
		last;
	}
	shift @ARGV;
}

if($nlines == 0 && @ARGV == 0){
	exec "xargs " . (length($\) ? '' : "echo -n");
}

$n = 0;
while(<>){
	chomp;
	push @lines, $_;
	if(++$n == $nlines){
		print join ' ', @lines;
		@lines = ();
		$n = 0;
	}
}
print join ' ', @lines if @lines;
