#!/usr/bin/perl

use warnings;

sub usage
{
	print "Usage: $0 src-file(s) dest-dir\n";
	print "Program to mkdir then $cmd\n";
	exit 1;
}

sub quote($)
{
	return "'$_[0]'";
}

sub basename($)
{
	my $_ = $_[0];
	return $1 if m|.*/([^/]+$)|;
	return $_;
}

sub mkdir_p($)
{
	$d = '';
	@d = map { $d = "$d/$_" } grep { length } split m|/|o, $_[0];

	if($_[0] !~ m|^/|){
		s|^/||o for @d;
	}

	for(@d){
		if(!-d $_){
			if($debug){
				print "mkdir '$_'\n";
			}else{
				mkdir $_ or die "mkdir $_: $!\n";
			}
		}
	}
	return 1;
}

$progname = basename($0);

if($progname eq 'mkcp'){
	$iscopy = 1;
}elsif($progname eq 'mkmv'){
	$iscopy = 0;
}else{
	die "Invalid program name \"$progname\", expected \"mkcp\" or \"mkmv\"\n";
}

usage if(@ARGV < 2 or $ARGV[0] eq '--help');

if($ARGV[0] eq '-d'){
	shift;
	$debug = 1;
}

$last  = $ARGV[$#ARGV];
@files = map { quote($_) } @ARGV[0 .. $#ARGV-1];

$cmd  = $iscopy ? 'cp' : 'mv';
$args = $iscopy ? '-R' : '';

mkdir_p($last);
if($debug){
	print "$cmd $args @files " . quote($last) . "\n";
}else{
	exec( "$cmd $args @files " . quote($last)) or die "exec(): $!$/";
}
