#!/usr/bin/perl

use warnings;

sub usage
{
	print "Usage: $0 src-file(s) dest-dir\n";
	print "Program to mkdir then $cmd\n";
	exit 1;
}

sub quote($)
{
	return "\"$_[0]\"";
}

sub basename($)
{
	my $_ = $_[0];
	return $1 if m|.*/([^/]+$)|;
	return $_;
}

$progname = basename($0);

if($progname eq 'mkcp'){
	$iscopy = 1;
}elsif($progname eq 'mkmv'){
	$iscopy = 0;
}else{
	die "Invalid program name \"$progname\", expected \"mkcp\" or \"mkmv\"\n";
}

usage if(@ARGV < 2 or $ARGV[0] eq '--help');

if($ARGV[0] eq '-d'){
	shift;
	$debug = 1;
}

$last  = $ARGV[$#ARGV];
@files = map { quote$_ } @ARGV[0 .. $#ARGV-1];

$cmd  = $iscopy ? 'cp' : 'mv';
$args = $iscopy ? '-R' : '';

if($debug){
	print "mkdir $last\n$cmd $args @files $last\n";
}else{
	if(!-d $last){
		mkdir $last or die "mkdir: $!$/";
	}
	system("$cmd $args @files ".quote$last) and die "system(): $!$/";
}
