#!/usr/bin/perl
use warnings;

sub usage()
{
	my $s = <<"!";
Usage: $0 [-v] [grep_args] -- [files]
 -v: verbose
!
	print STDERR $s;
	exit 1;
}

sub escape($)
{
	my $s = shift;
	$s =~ s/"/\\"/g;
	return $s;
}

my $verbose = 0;

if(@ARGV && $ARGV[0] eq '-v'){
	$verbose = 1;
	shift @ARGV;
}

$pivot = -1;

for my $i (0 .. $#ARGV){
	$pivot = $i if $ARGV[$i] eq '--';
}

usage if $pivot == -1;

my @gargs = @ARGV[0 .. $pivot - 1];
my @files = @ARGV[$pivot + 1 .. $#ARGV];

$red   = "\033[0;35m";
$nocol = "\033[0;00m";

open STDOUT, '| uniq';

my $found = 0;

for $f (@files){ # TODO: sort files
	my $cmd = "pdftotext \"" . escape($f) . "\" - 2>/dev/null | grep --color=always " .
		join(' ', map { "'$_'" } @gargs) . ' 2>/dev/null';

	for(my @out = `$cmd`){
		$found = 1;
		if($verbose){
			print "$red$f$nocol: " . join(' ', @out);
		}else{
			print "$f\n";
			last;
		}
	}
}

exit !$found;
