#!/usr/bin/perl
use strict;
use warnings;

use constant {
	INFINITY => "inf",
};

sub parse
{
	my @folk;
	while(<>){
		if(!/^([a-z]+) +(-?[0-9]+(\.[0-9]+)?)( (-?[0-9]+(\.[0-9]+)?))?$/){
			die "invalid line, expected <name> <balance> [desired]\n";
		}

		my($name, $balance, $desired) = ($1, $2, $5);
		push @folk, { name => $name, balance => $balance, desired => $desired };
	}
	return @folk;
}

sub balance_total
{
	my $total = 0;
	for(@_){
		$total += $_->{balance};
	}
	return $total;
}

my @folk = parse();
my $total = balance_total(@folk);
my $perperson = -$total / @folk;

sub get_desired
{
	my $p = shift;
	if(defined $p->{desired}){
		return -$p->{desired};
	}
	return -$perperson;
}

sub is_owed
{
	return $_->{balance} < get_desired($_);
}

sub find_max_owed
{
	my $lowest_balance = INFINITY;
	my $max = undef;

	for(@_){
		if(is_owed($_) and $_->{balance} < $lowest_balance){
			$lowest_balance = $_->{balance};
			$max = $_;
		}
	}

	if(!$max){
		die "no-one owes anyone any money?";
	}

	return $max;
}

sub equal_to_nearest_penny
{
	my($a, $b) = @_;
	return sprintf("%.2f", $a) eq sprintf("%.2f", $b);
}

sub currency_cmp
{
	my($a, $b) = @_;

	if(equal_to_nearest_penny($a, $b)){
		return 0;
	}

	return $a <=> $b;
}

for(@folk){
	while(currency_cmp($_->{balance}, get_desired($_)) > 0){
		my $to = find_max_owed(@folk);
		my $to_target = get_desired($to);
		my $diff = $to_target - $to->{balance};

		my $min = get_desired($_);
		if($_->{balance} - $diff < $min){
			$diff = $_->{balance} - $min;
		}

		$to->{balance} += $diff;
		$_->{balance} -= $diff;
		print "$_->{name} $diff --> $to->{name}\n";
	}
}
