#!/usr/bin/perl

sub ctrl_and
{
	return chr(ord(shift()) & 037);
}

my $erase = chr(127);
my $clrtoeol = "\x1b[K";
my $green = 32;
my $blue = 34;
my $os;
my $tab = ctrl_and('i');

sub stty
{
	my $flag = "-F";
	if($os eq "Darwin"){
		$flag = "-f";
	}
	system("stty $flag /dev/tty @_");
}

sub iserase
{
	my $ch = shift;
	return $ch eq $erase;
}

sub colour
{
	my($s, $col) = @_;
	return "\x1b[0;${col}m$s\x1b[0m";
}

sub uniq
{
	my %out;
	$out{$_} = 1 for @_;
	return keys %out;
}

sub finish
{
	my $ent = shift();
	print STDERR "\r$clrtoeol";
	if($ent){
		print "$ent\n";
	}
}

sub simplify
{
	my($str, $type) = @_;
	if($type == 'full'){
		$str =~ s;([^/])(?:[^/]+(/)|[^-]+(-));$1$2$3;g;
	}else{
		$str =~ s;([^/])(?:[^/]+(/)|[^-]+(-));$1 . substr("$2$3", 0, 3);ge;
	}
	return $str;
}

sub index_i
{
	my($s, $c, $start) = @_;
	return index(lc($s), lc($c), $start);
}

sub ordered
{
	sub chardistances
	{
		my($chars, $verbose) = @_;
		my $anchor = substr($choice, 0, 1);
		my $match = 999999999;
		my $match_v = '';
		my $start = 0;

		return $match unless length($choice);

		while(1){
			$start = index_i($chars, $anchor, $start);
			last if $start == -1;

			if(substr($chars, $start) !~ /$choice_re/i){
				last;
			}

			# got a match, record
			if(length($&) < $match){
				$match = length($&);
				$match_v = $&;
			}
			$start++;
		}

		if($verbose){
			return $match . " ($match_v)";
		}
		return $match;
	}

	my %distances = map { $_ => chardistances($_) } @_;
	return sort {
		my $distcmp = $distances{$a} <=> $distances{$b};
		return $distcmp if $distcmp;
		return length($a) <=> length($b);
	} @_;
}

sub reescape
{
	my $c = shift;
	my $special = ".+*[](){}";
	if(index($special, $c) >= 0){
		return "\\$c";
	}
	return $c;
}

chomp($os = `uname -s`);

sub highlight
{
	my($s, $first) = @_;

	if($s =~ /(.*)($choice_re)(.*)/i){
		my $col = $first ? $green : $blue;
		return $1 . colour($2, $col) . $3;
	}

	return $s;
}

$choice = "";
$after = "";
#$cursor_index = 0;
$prompt = "> ";
$prompt_len = length($prompt);
$print_all = 0;
$consecutive_tabs = 0;

if(@ARGV && ($ARGV[0] eq '--all' or $ARGV[0] eq '-a')){
	shift;
	$print_all = 1;
}

if(@ARGV){
	@choices = @ARGV;
}else{
	print STDERR "\r$0: loading...\r";
	@choices = map { chomp; $_ } <STDIN>;
	open STDIN, '<&STDERR' or die "couldn't reopen stdin: $!";
	print STDERR "$clrtoeol";
}

$| = 1;
sub stty_raw { stty("-icanon -echo"); }
sub stty_cooked { stty("icanon echo"); }
stty_raw();
END {
	my $ec = $?;
	stty_cooked();
	return $ec;
};

while(1){
	# filter --------------------------------
	($choice_re = $choice) =~ s/./reescape($&) . ".*?"/eg;

	$after = " [<no matches>]";
	eval {
		@relevant = grep /$choice_re/i, @choices;
		1;
	} or do {
		@relevant = ();
		$after = " [<regex error (/$choice_re/)>]";
	};

	my @ordered_relevant;
	my $after_verbatim = $after;
	if(@relevant){
		$columns = $ENV{COLUMNS} - 1;
		if($columns == -1){
			$columns = 80;
		}
		$space = $columns - $prompt_len - length($choice) - 3; # 3 for " []"
		$space_per_choice = ($space - @relevant * 2) / @relevant;

		my $attemptno = 0; # 0 - 2. 0=full strings, 1=medium simplify(), 2=full simplify()
		@ordered_relevant = ordered(@relevant);

		my @substrs;
		my $overflow;
		while(1){
			$overflow = 0;
			@substrs = ();

			for(@ordered_relevant){
				my $next;

				if($attemptno == 0){
					$next = $_;
				}elsif($attemptno == 1){
					if(@substrs < 3){
						$next = $_;
					}elsif(@substrs < 6){
						$next = simplify($_, 'medium');
					}else{
						$next = simplify($_, 'full');
					}
				}elsif($attemptno == 2){
					$next = simplify($_, 'medium');
				}elsif($attemptno == 3){
					$next = simplify($_, 'full');
				}

				if(length(join(", ", @substrs, $next, "...")) >= $space){
					$overflow = 1;
					last;
				}
				push @substrs, $next;
			}

			if($overflow and $attemptno < 2){
				$attemptno++;
			}else{
				last;
			}
		}

		if($overflow){
			push @substrs, "...";
		}

		$after_verbatim = " [" . join(", ", @substrs) . "]";
		if(@relevant == 1){
			$after = colour($after_verbatim, $green);
		}else{
			my $i = 1;
			$after = " [" . join(", ", map { highlight($_, $i++ == 1) } @substrs) . "]";
		}
	}

	# prompt --------------------------------
	print STDERR "\r$prompt$choice$after$clrtoeol";
	print STDERR "\x1b[D" x length($after_verbatim) ; # - (length($choice) - $cursor_index));

	if(read(STDIN, $ch, 1) != 1){
		exit(1);
	}

	if(!($ch eq $tab)){
		$consecutive_tabs = 0;
	}

	if(iserase($ch)){
		$choice =~ s/.$//;
		#$cursor_index--;

	}elsif(ord($ch) == 10){
		if($print_all && @relevant){
			for(@relevant){
				print "$_\n";
			}
			finish();
			last;
		}elsif(@ordered_relevant){
			finish($ordered_relevant[0]);
			last;
		}else{
			print STDERR "no matches\n";
		}

	}elsif($ch eq ctrl_and('w')){
		$choice =~ s/\b[a-zA-Z0-9]+$//;
		#$cursor_index -= length($&);

	}elsif($ch eq ctrl_and('u')){
		$choice = "";
		#$cursor_index = 0;

	#}elsif($ch eq ctrl_and('f')){
	#    if($cursor_index < length($choice)){
	#        $cursor_index++;
	#    }

	#}elsif($ch eq ctrl_and('b')){
	#    if($cursor_index > 0){
	#        $cursor_index--;
	#    }

	}elsif($ch eq $tab){
		$consecutive_tabs++;

		my $numselect = ($consecutive_tabs > 1);

		print STDERR "\n";
		my $a = @ordered_relevant ? \@ordered_relevant : \@relevant;
		my $i = 1;
		for(@$a){
			my $to_print = highlight($_, $i == 1);
			print STDERR ($numselect ? "$i " : "") . "$to_print\n";
			$i++;
		}

		if($numselect){
			$consecutive_tabs = 0;
			print STDERR "[number] > ";
			stty_cooked();
			my $num = <STDIN>;
			stty_raw();
			if($num !~ /^[0-9]+$/){
				print STDERR "invalid number '$num'\n";
			}else{
				my $chosen = (@$a)[$num - 1];
				if($chosen){
					finish($chosen);
					last;
				}
			}
		}

	}else{
		$choice .= $ch;
		#$cursor_index++;
	}
}
