#!/usr/bin/perl

our $base;

sub link_absolute($)
{
	local $_ = shift;

	return 1 if /^\//;
	return 1 if m#^[a-z]+://#;
	return 0;
}

sub scan($)
{
	local $_ = shift;

	$base = $1 if s#<base +href=["']([^"']+)['"]##;

	while(s/<(img|a) [^>]*(href|src)=(["'])([^"']+)\3[^>]*>//i){
		my $l = $4;
		if(!link_absolute($l)){
			$l = "$base/$l";
		}
		print $l;
	}
}

$\ = "\n";

if(@ARGV){
	for my $arg (@ARGV){
		my $f;
		if(-f $arg){
			$f = "< $arg";
		}else{
			$f = "wget -qO- $arg |";
			$base = $arg;
		}

		open F, $f or die "open $f\n";
		scan $_ for <F>;
		close F;
	}
}else{
	scan $_ while <STDIN>;
}
