#!/usr/bin/perl

sub scan($)
{
	local $_ = $_[0];
	print $4 while(s/<(img|a) [^>]*(href|src)=(["'])([^"']+)\3[^>]*>//i);
}

die "Usage: $0 [--help] [FILES...]\n" if $ARGV[0] eq '--help';

$\ = "\n";
$doneone = 0;

for $arg (@ARGV){
	if(-f $arg){
		$f = "< $arg";
	}else{
		$f = "wget -qO- $arg |";
	}

	open F, $f or die "open $f\n";
	scan $_ for <F>;
	close F;
	$doneone = 1;
}

if(!$doneone){
	scan $_ while(<STDIN>);
}
