#!/usr/bin/perl

sub scan($)
{
	local $_ = shift;
	print $4 while(s/<(img|a) [^>]*(href|src)=(["'])([^"']+)\3[^>]*>//i);
}

$\ = "\n";

if(@ARGV){
	for my $arg (@ARGV){
		my $f;
		if(-f $arg){
			$f = "< $arg";
		}else{
			$f = "wget -qO- $arg |";
		}

		open F, $f or die "open $f\n";
		scan $_ for <F>;
		close F;
	}
}else{
	scan $_ while <STDIN>;
}
